### ISSUE TITLE
Gradual stake onboarding

### ISSUE THREAD

**Issue by jrwbabylonlab** [babylonlabs-io/staking-api-service#127]
- API to accepte a config value to indicate the BBN height at which the all delegations can start "transition" to phase-2. (this BBN config height should compare the value of last processed BBN height from indexer db)
- API to accepte a config value to indicate the BTC height at which `staking_height < this btc height` can be transitioned into phase-- API to return a boolean value in one of the endpoint to indicate that the staking is now open. FE shall block the staking form until this value return true.
![Image](https://github.com/user-attachments/assets/50befb7b-ce59-425f-ab38-03b72fab3dea)

**Comment by jeremy-babylonlabs** [comment]
https://github.com/babylonlabs-io/simple-staking/commit/b868f52bff941a0a7508780f0e2b2bb59f0e01a3
